// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type TestGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/tests_controller.ts').default['index'], false>
}
export interface ApiDefinition {
  'test': {
    '$url': {
    };
    '$get': TestGetHead;
    '$head': TestGetHead;
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
